/* 쿠폰 */
CREATE TABLE coupon (
    couponIdx INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    couponCode VARCHAR(50) NOT NULL,
    discountPercent DECIMAL(10,2) NOT NULL,
    expirationDate DATETIME NOT NULL,
    isActive ENUM('y', 'n') DEFAULT 'n' NOT NULL
);

CREATE TABLE ad (
	adIdx INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	adTitle VARCHAR(100) NOT NULL,
	adContent TEXT,
	adImage VARCHAR(255) NOT NULL,
	startDate DATETIME DEFAULT NOW() NOT NULL,
	endDate DATETIME NOT NULL,
	createDate DATETIME DEFAULT NOW() NOT NULL
);

CREATE TABLE ad_log (
	adLogIdx INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	adIdx INT NOT NULL,
	userIdx INT NOT NULL,
	adDate DATETIME DEFAULT NOW()
);